// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkydokfyorlolbarcazl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRreWRva2Z5b3Jsb2xiYXJjYXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTA0NzksImV4cCI6MjA2ODkyNjQ3OX0.Y0OJFAljYaLhK-ycau68irPgSS6EgSzcrnxcT2ctdLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});